Fixing workflow to ensure .env file

diff --git a/.github/workflows/user-service.yml b/.github/workflows/user-service.yml
--- a/.github/workflows/user-service.yml
+++ b/.github/workflows/user-service.yml
@@ -18,6 +18,20 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Verify .env File
+        run: |
+          ls services/user-service/.env || echo ".env file is missing"
+
+      - name: Create .env File
+        run: |
+          echo "DATABASE_URL=postgresql://postgres:postgres@user-db:5432/user_service" > services/user-service/.env
+          echo "DATABASE_NAME=user_service" >> services/user-service/.env
+          echo "DATABASE_USER=postgres" >> services/user-service/.env
+          echo "DATABASE_PASSWORD=postgres" >> services/user-service/.env
+          echo "DATABASE_HOST=user-db" >> services/user-service/.env
+          echo "DATABASE_PORT=5432" >> services/user-service/.env
+          echo "SERVER_PORT=8000" >> services/user-service/.env
+
       - name: Set environment variables
         run: |
           echo "DATABASE_URL=postgresql://postgres:postgres@user-db:5432/user_service" >> $GITHUB_ENV
